"""add credit_limit, outstanding_balance, statement_due_date, minimum_due to accounts

Revision ID: 5e160c1bc782
Revises: 66dad9d194aa
Create Date: 2026-05-19 23:15:09.310397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e160c1bc782'
down_revision: Union[str, Sequence[str], None] = '66dad9d194aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('outstanding_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('statement_due_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('minimum_due', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'minimum_due')
    op.drop_column('accounts', 'statement_due_date')
    op.drop_column('accounts', 'outstanding_balance')
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
